application: helloworld1904
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: cloudApp.application

libraries:                                                                      
- name: jinja2                                                                  
  version: latest 